version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: -v start-dev --import-realm
    restart: always
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./src/keycloak:/opt/keycloak/data/import
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}:1433
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    healthcheck:
      test:
        - CMD
        - /opt/mssql-tools/bin/sqlcmd
        - -S
        - localhost
        - -U
        - ${DB_USER}
        - -P
        - ${DB_PASSWORD}
        - -Q
        - SELECT 1
        - -b
        - -o
        - /dev/null
      timeout: 5s
      interval: 10s
      retries: 10
      start_period: 10s
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    container_name: ${REDIS_HOST}
    image: redis:7
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
volumes:
  mssql: ~
  redis:
    driver: local
